### ISSUE TITLE
Continuing...

### ISSUE THREAD

**Issue by kenzierocks** [Organisation-Against-Sponge/OAS#2]
So your response is to just not communicate?

**Comment by kenzierocks** [comment]
I'm sorry, block me communicating?

**Comment by AgentTroll** [comment]
You must have an issue with it?

**Comment by AgentTroll** [comment]
Sorry small glitch from my phone.

**Comment by kenzierocks** [comment]
it cool man





No, I don't normally talk like that.

**Comment by AgentTroll** [comment]
Ok.

**Comment by kenzierocks** [comment]
More labels?

**Comment by AgentTroll** [comment]
Of course. Also please don't close this issue <3
